---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: ci-cd-pipeline-run
spec:
  pipelineRef:
    name: ci-cd-pipeline
  params:
    - name: repository-url
      value: https://github.com/Pangpang0255/ci-cd-final-project.git
    - name: app-name
      value: ci-cd-app
    - name: build-image
      value: image-registry.openshift-image-registry.svc:5000/default/ci-cd-app:latest
  workspaces:
    - name: output
      persistentVolumeClaim:
        claimName: oc-lab-pvc
